### ISSUE TITLE
k3s deployment/service status incorrect after a few restarts of both master nodes.

### ISSUE THREAD

**Issue by samirsss** [k3s-io/k3s#2290]
**Environmental Info:**
K3s Version: 
v1.18.6+k3s1 

Node(s) CPU architecture, OS, and Version: 
uname -a
Linux tpvm 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 Masters - **I understand this is not recommended but thats what one of our customer has**
Both running on Ubuntu 18.04
Mariadb is the backend for both using galera cluster.

**Describe the bug:**

Initial deployment of the application services is fine. However very occasionally when both nodes are rebooted together (to simulate a double fault, to check if there is a split brain), we see that only a few (4 services) are deployed on both nodes from the output

k3s kubectl -n <namespace> get pods -o wide

It takes a really long time (2-3 hours) for k3s to return back to a state of sanity if at all. In a lot of cases we've had to restart k3s using `systemctl restart k3s` on both nodes to get it to reflect the right deployment status and pods. 

I've verified that mariadb is functional and responds to all queries as needed. k3s database is available too.

**Steps To Reproduce:**

- Installed K3s: 
- deployed application
- restart both nodes together a few times (about 5-6 cycles)

**Expected behavior:**

All the pods/services to show up in the right state and if they need to be deployed - k3s should do it.

**Actual behavior:**

Only a few pods show up as deployed and running and rest of them are not shown.

**Additional context / logs:**

**Heres the application deployment state**

**kube-system pods are fine**

```
kube-system Pods :
NAME                       READY   STATUS    RESTARTS   AGE     IP             NODE    NOMINATED NODE   READINESS GATES
node-local-dns-266pf       1/1     Running   44         2d4h    10.20.62.209   tpvm2   <none>           <none>
coredns-6dbbdcb79c-q7tf8   1/1     Running   0          7m21s   10.42.0.251    tpvm2   <none>           <none>
node-local-dns-sj9bx       1/1     Running   8          2d4h    10.20.62.235   tpvm1   <none>           <none>
coredns-6dbbdcb79c-gg7jn   1/1     Running   2          8h      10.42.2.109    tpvm1   <none>           <none>
traefik-7b487b687b-gsxlb   1/1     Running   2          8h      10.42.2.111    tpvm1   <none>           <none>

Nodes :
NAME    STATUS   ROLES    AGE    VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME         LABELS
tpvm2   Ready    master   2d4h   v1.18.6+k3s1   10.20.62.209   <none>        Ubuntu 18.04.4 LTS   5.3.0-40-generic   containerd://1.3.3-k3s2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,keepalived=standby,kubernetes.io/arch=amd64,kubernetes.io/hostname=tpvm2,kubernetes.io/os=linux,node-role.kubernetes.io/master=true
tpvm1   Ready    master   2d4h   v1.18.6+k3s1   10.20.62.235   <none>        Ubuntu 18.04.4 LTS   5.3.0-40-generic   containerd://1.3.3-k3s2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,keepalived=active,kubernetes.io/arch=amd64,kubernetes.io/hostname=tpvm1,kubernetes.io/os=linux,node-role.kubernetes.io/master=true

EFA Application status:
NAME                                   READY   STATUS    RESTARTS   AGE     IP             NODE    NOMINATED NODE   READINESS GATES
**pod/gosystem-service-df9698f84-2mr2z   1/1     Running   0          7m23s   10.20.62.209   tpvm2   <none>           <none>
pod/gosystem-service-df9698f84-6gkwx   1/1     Running   2          8h      10.20.62.235   tpvm1   <none>           <none>
pod/rabbitmq-1                         1/1     Running   0          6m48s   10.42.0.250    tpvm2   <none>           <none>
pod/rabbitmq-0                         1/1     Running   2          8h      10.42.2.110    tpvm1   <none>           <none>**
```

**None of the pods shown in bold are displayed as running**

```
NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                          AGE    SELECTOR
service/rabbitmq                 NodePort    10.43.204.76    <none>        15672:31672/TCP,5672:30672/TCP   2d4h   app=rabbitmq
**service/gofabric-service         ClusterIP   10.43.208.65    <none>        8081/TCP                         2d4h   app=gofabric-service
service/goinventory-service      ClusterIP   10.43.74.184    <none>        8082/TCP                         2d4h   app=goinventory-service
service/gotenant-service         ClusterIP   10.43.110.155   <none>        8083/TCP                         2d4h   app=gotenant-service
service/efa-api-docs             ClusterIP   10.43.26.39     <none>        80/TCP                           2d4h   app=efa-api-docs**
**service/goraslog-service         ClusterIP   10.43.38.223    <none>        8091/TCP                         2d4h   app=goraslog-service
service/gonotification-service   ClusterIP   10.43.158.233   <none>        8088/TCP                         2d4h   app=gonotification-service
service/goauth-service           ClusterIP   10.43.154.7     <none>        8080/TCP                         2d4h   app=goauth-service
service/gorbac-service           ClusterIP   10.43.193.1     <none>        8089/TCP                         2d4h   app=gorbac-service
service/goopenstack-service      ClusterIP   10.43.114.235   <none>        8085/TCP                         2d4h   app=goopenstack-service
service/govcenter-service        ClusterIP   10.43.164.52    <none>        8086/TCP                         2d4h   app=govcenter-service
service/gohyperv-service         ClusterIP   10.43.244.106   <none>        8087/TCP                         2d4h   app=gohyperv-service**
service/gosystem-service         ClusterIP   10.43.128.150   <none>        8090/TCP                         2d4h   app=gosystem-service

NAME                               READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES           SELECTOR
deployment.apps/gosystem-service   2/2     2            2           47h   gosystem     gosystem:2.3.0   app=gosystem-service

NAME                                         DESIRED   CURRENT   READY   AGE   CONTAINERS   IMAGES           SELECTOR
replicaset.apps/gosystem-service-df9698f84   2         2         2       47h   gosystem     gosystem:2.3.0   app=gosystem-service,pod-template-hash=df9698f84

NAME                        READY   AGE   CONTAINERS      IMAGES
statefulset.apps/rabbitmq   2/2     47h   rabbitmq-node   rabbitmq:2.3.0
```

**Snippet from k3s log**

```
UTC m=+84.188481318) (total time: 825.040748ms):
Sep 21 04:41:59 tpvm1 k3s[6898]: Trace[828730383]: [210.253647ms] [148.022431ms] Transaction committed
Sep 21 04:41:59 tpvm1 k3s[6898]: Trace[828730383]: [824.788648ms] [597.583792ms] Transaction committed
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.325841    6898 trace.go:116] Trace[1910865096]: "Patch" url:/api/v1/nodes/tpvm1/status,user-agent:k3s/v1.18.6+k3s1 (linux/amd64) kubernetes/6f56fa1,client:127.0.0.1 (started: 2020-09-21 04:41:58.499442872 +0000 UTC m=+84.187910903) (total time: 826.345513ms):
Sep 21 04:41:59 tpvm1 k3s[6898]: Trace[1910865096]: [211.024937ms] [164.592602ms] About to apply patch
Sep 21 04:41:59 tpvm1 k3s[6898]: Trace[1910865096]: [825.74856ms] [602.701377ms] Object stored in database
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.337388    6898 flannel.go:78] Wrote subnet file to /run/flannel/subnet.env
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.337436    6898 flannel.go:82] Running backend.
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.337460    6898 vxlan_network.go:60] watching for new subnet leases
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.341740    6898 iptables.go:145] Some iptables rules are missing; deleting and recreating rules
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.341791    6898 iptables.go:167] Deleting iptables rule: -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.346613    6898 iptables.go:145] Some iptables rules are missing; deleting and recreating rules
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.346663    6898 iptables.go:167] Deleting iptables rule: -s 10.42.0.0/16 -j ACCEPT
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.348736    6898 iptables.go:167] Deleting iptables rule: -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.351873    6898 iptables.go:167] Deleting iptables rule: -d 10.42.0.0/16 -j ACCEPT
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.353126    6898 iptables.go:167] Deleting iptables rule: ! -s 10.42.0.0/16 -d 10.42.2.0/24 -j RETURN
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.357227    6898 iptables.go:155] Adding iptables rule: -s 10.42.0.0/16 -j ACCEPT
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.357778    6898 iptables.go:167] Deleting iptables rule: ! -s 10.42.0.0/16 -d 10.42.0.0/16 -j MASQUERADE --random-fully
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.364990    6898 iptables.go:155] Adding iptables rule: -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.368728    6898 iptables.go:155] Adding iptables rule: -d 10.42.0.0/16 -j ACCEPT
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.378027    6898 iptables.go:155] Adding iptables rule: -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.401472    6898 iptables.go:155] Adding iptables rule: ! -s 10.42.0.0/16 -d 10.42.2.0/24 -j RETURN
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.407979    6898 iptables.go:155] Adding iptables rule: ! -s 10.42.0.0/16 -d 10.42.0.0/16 -j MASQUERADE --random-fully
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.598824    6898 trace.go:116] Trace[461530964]: "GuaranteedUpdate etcd3" type:*core.Node (started: 2020-09-21 04:41:58.841194832 +0000 UTC m=+84.529662917) (total time: 757.577244ms):
Sep 21 04:41:59 tpvm1 k3s[6898]: Trace[461530964]: [298.637888ms] [295.065824ms] Transaction committed
Sep 21 04:41:59 tpvm1 k3s[6898]: Trace[461530964]: [613.0544ms] [284.380964ms] Transaction committed
Sep 21 04:41:59 tpvm1 k3s[6898]: Trace[461530964]: [757.362642ms] [140.77655ms] Transaction committed
Sep 21 04:41:59 tpvm1 k3s[6898]: I0921 04:41:59.599537    6898 trace.go:116] Trace[1890489218]: "Patch" url:/api/v1/nodes/tpvm1/status,user-agent:k3s/v1.18.6+k3s1 (linux/amd64) kubernetes/6f56fa1,client:127.0.0.1 (started: 2020-09-21 04:41:58.840978204 +0000 UTC m=+84.529446224) (total time: 758.496695ms):
Sep 21 04:41:59 tpvm1 k3s[6898]: Trace[1890489218]: [299.019289ms] [295.887714ms] About to apply patch
Sep 21 04:41:59 tpvm1 k3s[6898]: Trace[1890489218]: [613.457856ms] [285.273143ms] About to apply patch
Sep 21 04:41:59 tpvm1 k3s[6898]: Trace[1890489218]: [757.928449ms] [141.813096ms] Object stored in database
Sep 21 04:42:00 tpvm1 k3s[6898]: I0921 04:42:00.215171    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-l7qm7" (UniqueName: "kubernetes.io/secret/b8b4eca1-6108-4638-8159-f6b6aa905042-default-token-l7qm7") pod "gosystem-service-df9698f84-6gkwx" (UID: "b8b4eca1-6108-4638-8159-f6b6aa905042")
Sep 21 04:42:00 tpvm1 k3s[6898]: I0921 04:42:00.215275    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "containerd-vol" (UniqueName: "kubernetes.io/host-path/b8b4eca1-6108-4638-8159-f6b6aa905042-containerd-vol") pod "gosystem-service-df9698f84-6gkwx" (UID: "b8b4eca1-6108-4638-8159-f6b6aa905042")
Sep 21 04:42:00 tpvm1 k3s[6898]: I0921 04:42:00.215558    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "gosystem-log-pv" (UniqueName: "kubernetes.io/host-path/b8b4eca1-6108-4638-8159-f6b6aa905042-gosystem-log-pv") pod "gosystem-service-df9698f84-6gkwx" (UID: "b8b4eca1-6108-4638-8159-f6b6aa905042")
Sep 21 04:42:00 tpvm1 k3s[6898]: I0921 04:42:00.215781    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "timezone" (UniqueName: "kubernetes.io/host-path/b8b4eca1-6108-4638-8159-f6b6aa905042-timezone") pod "gosystem-service-df9698f84-6gkwx" (UID: "b8b4eca1-6108-4638-8159-f6b6aa905042")
Sep 21 04:42:00 tpvm1 k3s[6898]: I0921 04:42:00.215938    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "master-node" (UniqueName: "kubernetes.io/configmap/b8b4eca1-6108-4638-8159-f6b6aa905042-master-node") pod "gosystem-service-df9698f84-6gkwx" (UID: "b8b4eca1-6108-4638-8159-f6b6aa905042")
Sep 21 04:42:00 tpvm1 k3s[6898]: I0921 04:42:00.316293    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/9aa71317-c2b5-4d81-934e-86ce2205c4e0-config-volume") pod "rabbitmq-0" (UID: "9aa71317-c2b5-4d81-934e-86ce2205c4e0")
Sep 21 04:42:00 tpvm1 k3s[6898]: E0921 04:42:00.618946    6898 remote_runtime.go:128] StopPodSandbox "6b367d2095ec346ab27a5c9a52ea4f6c1e206e714dca79e82de1ba777bb961d9" from runtime service failed: rpc error: code = Unknown desc = an error occurred when try to find sandbox "6b367d2095ec346ab27a5c9a52ea4f6c1e206e714dca79e82de1ba777bb961d9": does not exist
Sep 21 04:42:00 tpvm1 k3s[6898]: E0921 04:42:00.619041    6898 kuberuntime_manager.go:895] Failed to stop sandbox {"containerd" "6b367d2095ec346ab27a5c9a52ea4f6c1e206e714dca79e82de1ba777bb961d9"}
Sep 21 04:42:00 tpvm1 k3s[6898]: E0921 04:42:00.619135    6898 kuberuntime_manager.go:674] killPodWithSyncResult failed: failed to "KillPodSandbox" for "b8b4eca1-6108-4638-8159-f6b6aa905042" with KillPodSandboxError: "rpc error: code = Unknown desc = an error occurred when try to find sandbox \"6b367d2095ec346ab27a5c9a52ea4f6c1e206e714dca79e82de1ba777bb961d9\": does not exist"
Sep 21 04:42:00 tpvm1 k3s[6898]: E0921 04:42:00.619195    6898 pod_workers.go:191] Error syncing pod b8b4eca1-6108-4638-8159-f6b6aa905042 ("gosystem-service-df9698f84-6gkwx_efa(b8b4eca1-6108-4638-8159-f6b6aa905042)"), skipping: failed to "KillPodSandbox" for "b8b4eca1-6108-4638-8159-f6b6aa905042" with KillPodSandboxError: "rpc error: code = Unknown desc = an error occurred when try to find sandbox \"6b367d2095ec346ab27a5c9a52ea4f6c1e206e714dca79e82de1ba777bb961d9\": does not exist"
Sep 21 04:42:00 tpvm1 k3s[6898]: I0921 04:42:00.877256    6898 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: f8421036708a5e1b6d973d44b3999735b9bcc64aa6dbfc3419635f256d7ab753
Sep 21 04:42:01 tpvm1 k3s[6898]: I0921 04:42:01.019400    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "config" (UniqueName: "kubernetes.io/configmap/67a440e7-b008-405d-894f-be23e54e16ad-config") pod "traefik-7b487b687b-gsxlb" (UID: "67a440e7-b008-405d-894f-be23e54e16ad")
Sep 21 04:42:01 tpvm1 k3s[6898]: I0921 04:42:01.019495    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "ssl" (UniqueName: "kubernetes.io/secret/67a440e7-b008-405d-894f-be23e54e16ad-ssl") pod "traefik-7b487b687b-gsxlb" (UID: "67a440e7-b008-405d-894f-be23e54e16ad")
Sep 21 04:42:01 tpvm1 k3s[6898]: I0921 04:42:01.019566    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "traefik-token-r46zr" (UniqueName: "kubernetes.io/secret/67a440e7-b008-405d-894f-be23e54e16ad-traefik-token-r46zr") pod "traefik-7b487b687b-gsxlb" (UID: "67a440e7-b008-405d-894f-be23e54e16ad")
Sep 21 04:42:01 tpvm1 k3s[6898]: I0921 04:42:01.019731    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "rabbitmq-log-pv" (UniqueName: "kubernetes.io/host-path/9aa71317-c2b5-4d81-934e-86ce2205c4e0-rabbitmq-log-pv") pod "rabbitmq-0" (UID: "9aa71317-c2b5-4d81-934e-86ce2205c4e0")
Sep 21 04:42:01 tpvm1 k3s[6898]: I0921 04:42:01.020021    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "rabbitmq-token-47gpx" (UniqueName: "kubernetes.io/secret/9aa71317-c2b5-4d81-934e-86ce2205c4e0-rabbitmq-token-47gpx") pod "rabbitmq-0" (UID: "9aa71317-c2b5-4d81-934e-86ce2205c4e0")
Sep 21 04:42:01 tpvm1 k3s[6898]: W0921 04:42:01.049304    6898 kuberuntime_container.go:758] No ref for container {"containerd" "f8421036708a5e1b6d973d44b3999735b9bcc64aa6dbfc3419635f256d7ab753"}
Sep 21 04:42:01 tpvm1 k3s[6898]: I0921 04:42:01.826736    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "coredns-token-gztjp" (UniqueName: "kubernetes.io/secret/a6931c84-6426-496c-9959-12e755897cd1-coredns-token-gztjp") pod "coredns-6dbbdcb79c-gg7jn" (UID: "a6931c84-6426-496c-9959-12e755897cd1")
Sep 21 04:42:01 tpvm1 k3s[6898]: I0921 04:42:01.826907    6898 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/a6931c84-6426-496c-9959-12e755897cd1-config-volume") pod "coredns-6dbbdcb79c-gg7jn" (UID: "a6931c84-6426-496c-9959-12e755897cd1")
Sep 21 04:42:01 tpvm1 k3s[6898]: I0921 04:42:01.826944    6898 reconciler.go:157] Reconciler: start to sync state
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.035028    6898 remote_runtime.go:128] StopPodSandbox "484b2c97584008d0dd73e2c0993acc4ef444800bb6b41b97baed245d06cfd8c2" from runtime service failed: rpc error: code = Unknown desc = an error occurred when try to find sandbox "484b2c97584008d0dd73e2c0993acc4ef444800bb6b41b97baed245d06cfd8c2": does not exist
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.035114    6898 kuberuntime_manager.go:895] Failed to stop sandbox {"containerd" "484b2c97584008d0dd73e2c0993acc4ef444800bb6b41b97baed245d06cfd8c2"}
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.035205    6898 kuberuntime_manager.go:674] killPodWithSyncResult failed: failed to "KillPodSandbox" for "9aa71317-c2b5-4d81-934e-86ce2205c4e0" with KillPodSandboxError: "rpc error: code = Unknown desc = an error occurred when try to find sandbox \"484b2c97584008d0dd73e2c0993acc4ef444800bb6b41b97baed245d06cfd8c2\": does not exist"
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.035274    6898 pod_workers.go:191] Error syncing pod 9aa71317-c2b5-4d81-934e-86ce2205c4e0 ("rabbitmq-0_efa(9aa71317-c2b5-4d81-934e-86ce2205c4e0)"), skipping: failed to "KillPodSandbox" for "9aa71317-c2b5-4d81-934e-86ce2205c4e0" with KillPodSandboxError: "rpc error: code = Unknown desc = an error occurred when try to find sandbox \"484b2c97584008d0dd73e2c0993acc4ef444800bb6b41b97baed245d06cfd8c2\": does not exist"
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.063837    6898 remote_runtime.go:128] StopPodSandbox "801ee008449e4e3235a97efe431f44603b89fc9fd6c7f0dd69b0b30b8779d484" from runtime service failed: rpc error: code = Unknown desc = an error occurred when try to find sandbox "801ee008449e4e3235a97efe431f44603b89fc9fd6c7f0dd69b0b30b8779d484": does not exist
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.063972    6898 kuberuntime_manager.go:895] Failed to stop sandbox {"containerd" "801ee008449e4e3235a97efe431f44603b89fc9fd6c7f0dd69b0b30b8779d484"}
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.064062    6898 kuberuntime_manager.go:674] killPodWithSyncResult failed: failed to "KillPodSandbox" for "67a440e7-b008-405d-894f-be23e54e16ad" with KillPodSandboxError: "rpc error: code = Unknown desc = an error occurred when try to find sandbox \"801ee008449e4e3235a97efe431f44603b89fc9fd6c7f0dd69b0b30b8779d484\": does not exist"
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.064121    6898 pod_workers.go:191] Error syncing pod 67a440e7-b008-405d-894f-be23e54e16ad ("traefik-7b487b687b-gsxlb_kube-system(67a440e7-b008-405d-894f-be23e54e16ad)"), skipping: failed to "KillPodSandbox" for "67a440e7-b008-405d-894f-be23e54e16ad" with KillPodSandboxError: "rpc error: code = Unknown desc = an error occurred when try to find sandbox \"801ee008449e4e3235a97efe431f44603b89fc9fd6c7f0dd69b0b30b8779d484\": does not exist"
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.326670    6898 remote_runtime.go:128] StopPodSandbox "b9fe6430019ea5b39f1c9309de7cd15b140f93de2a56127adf1177cdcb06c7d4" from runtime service failed: rpc error: code = Unknown desc = an error occurred when try to find sandbox "b9fe6430019ea5b39f1c9309de7cd15b140f93de2a56127adf1177cdcb06c7d4": does not exist
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.326753    6898 kuberuntime_manager.go:895] Failed to stop sandbox {"containerd" "b9fe6430019ea5b39f1c9309de7cd15b140f93de2a56127adf1177cdcb06c7d4"}
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.326845    6898 kuberuntime_manager.go:674] killPodWithSyncResult failed: failed to "KillPodSandbox" for "a6931c84-6426-496c-9959-12e755897cd1" with KillPodSandboxError: "rpc error: code = Unknown desc = an error occurred when try to find sandbox \"b9fe6430019ea5b39f1c9309de7cd15b140f93de2a56127adf1177cdcb06c7d4\": does not exist"
Sep 21 04:42:03 tpvm1 k3s[6898]: E0921 04:42:03.326897    6898 pod_workers.go:191] Error syncing pod a6931c84-6426-496c-9959-12e755897cd1 ("coredns-6dbbdcb79c-gg7jn_kube-system(a6931c84-6426-496c-9959-12e755897cd1)"), skipping: failed to "KillPodSandbox" for "a6931c84-6426-496c-9959-12e755897cd1" with KillPodSandboxError: "rpc error: code = Unknown desc = an error occurred when try to find sandbox \"b9fe6430019ea5b39f1c9309de7cd15b140f93de2a56127adf1177cdcb06c7d4\": does not exist"
Sep 21 04:42:04 tpvm1 k3s[6898]: I0921 04:42:04.948399    6898 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 69c3df5bd22e77698bbac65c62f6593ddf5669748fa44f6f15dcc06f462ca440
Sep 21 04:47:27 tpvm1 k3s[6898]: I0921 04:47:27.577530    6898 log.go:172] http: TLS handshake error from 127.0.0.1:40308: EOF
Sep 21 04:48:41 tpvm1 k3s[6898]: I0921 04:48:41.176989    6898 log.go:172] http: TLS handshake error from 127.0.0.1:41090: EOF
Sep 21 04:48:41 tpvm1 k3s[6898]: I0921 04:48:41.177163    6898 log.go:172] http: TLS handshake error from 127.0.0.1:41082: EOF
Sep 21 04:48:46 tpvm1 k3s[6898]: I0921 04:48:46.209068    6898 log.go:172] http: TLS handshake error from 127.0.0.1:41564: EOF
Sep 21 04:48:46 tpvm1 k3s[6898]: I0921 04:48:46.214946    6898 log.go:172] http: TLS handshake error from 127.0.0.1:41566: EOF
Sep 21 04:48:49 tpvm1 k3s[6898]: I0921 04:48:49.921872    6898 log.go:172] http: TLS handshake error from 127.0.0.1:41828: EOF
Sep 21 04:48:51 tpvm1 k3s[6898]: I0921 04:48:51.886601    6898 log.go:172] http: TLS handshake error from 127.0.0.1:41986: EOF
Sep 21 04:48:55 tpvm1 k3s[6898]: I0921 04:48:55.764969    6898 log.go:172] http: TLS handshake error from 127.0.0.1:42276: EOF
Sep 21 04:48:55 tpvm1 k3s[6898]: I0921 04:48:55.769969    6898 log.go:172] http: TLS handshake error from 127.0.0.1:42272: EOF
Sep 21 04:48:55 tpvm1 k3s[6898]: I0921 04:48:55.770240    6898 log.go:172] http: TLS handshake error from 127.0.0.1:42270: EOF
Sep 21 04:48:55 tpvm1 k3s[6898]: I0921 04:48:55.770474    6898 log.go:172] http: TLS handshake error from 127.0.0.1:42266: EOF
```

**Comment by samirsss** [comment]
Bump on this one to get some 👀

**Comment by brandond** [comment]
Two nodes is fine for Kuberenetes. Can you reproduce this with a traditional mysql instance, or without keepalived? I don't have any sort of smoking gun for either, but those are both interesting departures from a stock configuration.

When you say the "pods are not running" - what exactly do you mean? Kubernetes clearly thinks they are. Do you have some output from crictl or docker (depending on your backend) showing the containers for those pods in some other state?

**Comment by samirsss** [comment]
Thanks @brandond - i'll get the details when I reproduce the issues. 

The pods dont show up as running when we run `k3s kubectl -n <namespace> get pods`, they seem to show up in the deployment. In most cases restarting k3s service seems to fix the issue, which to me implies that its not a Kubernetes issue, but a k3s issue causing it to not reconcile properly. The other pods are missing (not shown as Terminated/Init/Running or any other state)

Keepalived is just used to ensure Virtual IP fails over and the keepalived scripts help up cordon and uncordon a node and very importantly label the nodes. Its not directly playing a role in k3s function.

We cant use mysql - k3s uses the mariadb cluster as its backend as well.

**Comment by brandond** [comment]
> The pods dont show up as running when we run `k3s kubectl -n <namespace> get pods`, they seem to show up in the deployment. In most cases restarting k3s service seems to fix the issue, which to me implies that its not a Kubernetes issue, but a k3s issue causing it to not reconcile properly. The other pods are missing (not shown as Terminated/Init/Running or any other state)

You're saying that the deployment's pod counts (ready/up-to-date/available) don't line up with the actual number of pods?

> We cant use mysql - k3s uses the mariadb cluster as its backend as well.

Right, I don't necessarily mean mysql, mariadb is fine - I just mean do you get the same behavior from a non-clustered database?

**Comment by samirsss** [comment]
> You're saying that the deployment's pod counts (ready/up-to-date/available) don't line up with the actual number of pods?

Yes the pod counts dont line up with the actual number of pods. I am not sure if the Reconciliation.go isnt kicking in or something.

> Right, I don't necessarily mean mysql, mariadb is fine - I just mean do you get the same behavior from a non-clustered database?

Yep its the same behavior with Clustered vs Non Clustered DB.

**Comment by samirsss** [comment]
The above issue might be related to the bug in kine https://github.com/rancher/kine/issues/61 that was fixed recently and hence i'll check if the newer release of k3s fixes this issue as well

**Comment by brandond** [comment]
That bug was only present in a limited number of k3s releases so it's unlikely that it's the cause of what you were running into. I am curious if a newer release still shows this behavior though.
