### ISSUE TITLE
K3s 1.20.x debug logs show FIXME error every 10 seconds

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2616]
**Environmental Info:**
K3s Version: 
k3s version v1.20.0-rc.0+k3s-55a6dbc2-dirty (55a6dbc2)

Node(s) CPU architecture, OS, and Version: 
N/A

Cluster Configuration:
N/A

**Describe the bug:**
cadvisor in kubelet tries to check docker version even when using containerd, and the docker client library does not properly handle the resulting error when the socket does not exist. When run at debug level, it logs an error twice every 10 seconds:

```
time="2020-12-02T14:37:02.844548992-08:00" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1
time="2020-12-02T14:37:02.844650093-08:00" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1
time="2020-12-02T14:37:07.566816160-08:00" level=debug msg="Wrote ping"
time="2020-12-02T14:37:12.566841586-08:00" level=debug msg="Wrote ping"
time="2020-12-02T14:37:12.857020319-08:00" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1
time="2020-12-02T14:37:12.857132489-08:00" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1
```

Adding an additional log call to the code shows:
```
time="2020-12-02T14:37:12.856987707-08:00" level=debug msg="doRequest returned err=client.errConnectionFailed{host:\"unix:///var/run/docker.sock\"}"
```

**Steps To Reproduce:**
* Start K3s 1.20.x with --debug

**Expected behavior:**
No extra errors in logs

**Actual behavior:**
Errors

**Additional context / logs:**
Probably going to fork moby/moby, but the fix will need to be pulled through both cadvisor and kubelet. Kubelet is in the process of dropping native Docker support entirely so I'm not sure what the fate of cadvisor is to be.

**Comment by katran001** [comment]
Fixed upstream in newer releases; can close out.

**Comment by VestigeJ** [comment]
I seem to be seeing this issue cropping up again on COMMIT=b1a3ad0aa292956eac6552dd28b8b29819aacfa4
$ k3s -v
k3s version v1.22.9+k3s-b1a3ad0a (b1a3ad0a)
go version go1.16.10

$ sudo journalctl -u k3s | grep -i -e fixme | wc -l
2030

$ sudo journalctl -u k3s | grep -i -e fixme
```
May 25 21:57:03 ip-172-31-22-106 k3s[43466]: time="2022-05-25T21:57:03Z" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1
May 25 21:57:13 ip-172-31-22-106 k3s[43466]: time="2022-05-25T21:57:13Z" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1
May 25 21:57:13 ip-172-31-22-106 k3s[43466]: time="2022-05-25T21:57:13Z" level=debug msg="FIXME: Got an status-code for which error does not match any expected type!!!: -1" module=api status_code=-1
```

**Comment by brandond** [comment]
For the record: this is caused by cadvisor trying to collect statistics from the Docker socket even when Docker isn't in use. Its just one of many things that still don't work quite right when not using dockershim. I'm optimistic that they will get addressed over time now that dockershim is finally dead and upstream is forced to deal with these sorts of issues.
