### ISSUE TITLE
[k3s-upgrade] Upgrade to 1.22 from 1.21.4

### ISSUE THREAD

**Issue by adi90x** [k3s-io/k3s#3997]
Hello, 

Trying to test system-upgrade-controller, using default plan to run k3s-upgrade.
When updating control-plane node from 1.21.4 to 1.22 in an etcd embeded cluster, master node failed to restart with the below error : 
`{"level":"warn","ts":"2021-09-12T14:44:58.422Z","caller":"membership/cluster.go:427","msg":"skipped removing already removed member","cluster-id":"2dd222bcc6e5b129","local-member-id":"28e2acae05a66f61","removed-remote-peer-id":"95703eb04ef73011"}
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: {"level":"panic","ts":"2021-09-12T14:44:58.422Z","caller":"rafthttp/transport.go:346","msg":"unexpected removal of unknown remote peer","remote-peer-id":"95703eb04ef73011","stacktrace":"github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).removePeer\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/transport.go:346\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).RemovePeer\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/transport.go:329\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyConfChange\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:2303\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).apply\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:2135\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyEntries\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1357\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyAll\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1179\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).run.func8\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1111\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule.(*fifo).run\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule/schedule.go:157"}
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: panic: unexpected removal of unknown remote peer
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: goroutine 402 [running]:
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: github.com/rancher/k3s/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x400083ec00, 0x40117e6e40, 0x1, 0x1)
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.uber.org/zap/zapcore/entry.go:234 +0x418
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: github.com/rancher/k3s/vendor/go.uber.org/zap.(*Logger).Panic(0x4000c47040, 0x44dca5c, 0x29, 0x40117e6e40, 0x1, 0x1)
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.uber.org/zap/logger.go:227 +0x74
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).removePeer(0x4000348fc0, 0x95703eb04ef73011)
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/transport.go:346 +0x3f8
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).RemovePeer(0x4000348fc0, 0x95703eb04ef73011)
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/transport.go:329 +0x70
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyConfChange(0x4000eefc00, 0x1, 0x95703eb04ef73011, 0x0, 0x0, 0x0, 0x8df17bd7f905bee7, 0x40015d0f80, 0x0, 0x0, ...)
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:2303 +0x650
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).apply(0x4000eefc00, 0x400a1706f0, 0x41e, 0x3930, 0x40015d0f80, 0x4068b4, 0x400b9c1f78, 0x400b9c1f30)
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:2135 +0x400
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyEntries(0x4000eefc00, 0x40015d0f80, 0x400d581d90)
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1357 +0xb0
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyAll(0x4000eefc00, 0x40015d0f80, 0x400d581d90)
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1179 +0x5c
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).run.func8(0x4e2e7d8, 0x4000a59800)
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1111 +0x38
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule.(*fifo).run(0x4000cf0a20)
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule/schedule.go:157 +0xf0
sept. 12 14:44:58 oracle-vm-arm k3s[230758]: created by github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule.NewFIFOScheduler
sept. 12 14:44:58 oracle-vm-arm k3s[230758]:         /go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule/schedule.go:70 +0x138
`

Sorry for formating not sure there is an easier way to share this ? 

Main issue seems to be : `panic:  unexpected removal of unknown remote peer`

Regards,

**Comment by brandond** [comment]
I'm confused as to why it's even trying to remove a member from the etcd cluster. Are you deleting nodes from the cluster during the upgrade? Can you attach the full K3s service log, as well as the output of `kubectl get nodes -o yaml` ?

**Comment by adi90x** [comment]
In fact, I am not able to reproduce the same issue, however it seems that upgrading one node (using k3s-upgrade) of an HA cluster, the upgraded node try to connect to external IP  of other master instead of internal IP.
Everything was fine before and after upgrading one node I got several warning on the upgraded node logs 

`sept. 13 12:26:27 vm-k3s k3s[2484348]: {"level":"warn","ts":"2021-09-13T12:26:27.493Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"f211a528cb9e0be1","rtt":"0s","error":"dial tcp XXX.XXX.XXX.XXX:2380: connect: connection refused"}` 

It seems the upgraded node etcd add external IP as member to the cluster ( so basically all peers are doubled)  not sure if it is a feature or a bug 🤷‍♂️
Maybe it is link to etcd upgrade to 3.5 ? 

Regards, 
Adrien

**Comment by brandond** [comment]
That's interesting, and not something I've seen before. Can you attach the requested information?

**Comment by liyimeng** [comment]
For me I have something like this:

```
time="2021-11-17T22:15:31+08:00" level=info msg="Node token is available at /var/lib/rancher/k3s/server/token"
time="2021-11-17T22:15:31+08:00" level=info msg="To join node to cluster: k3s agent -s https://192.168.119.154:6443 -t ${NODE_TOKEN}"
time="2021-11-17T22:15:31+08:00" level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
time="2021-11-17T22:15:31+08:00" level=info msg="Run: k3s kubectl"
{"level":"info","ts":"2021-11-17T22:15:31.468+0800","caller":"rafthttp/pipeline.go:85","msg":"stopped HTTP pipelining with remote peer","local-member-id":"dd19be2118b49e84","remote-peer-id":"265f9398ef1e82cd"}
{"level":"info","ts":"2021-11-17T22:15:31.468+0800","caller":"rafthttp/stream.go:442","msg":"stopped stream reader with remote peer","stream-reader-type":"stream MsgApp v2","local-member-id":"dd19be2118b49e84","remote-peer-id":"265f9398ef1e82cd"}
{"level":"info","ts":"2021-11-17T22:15:31.468+0800","caller":"rafthttp/stream.go:442","msg":"stopped stream reader with remote peer","stream-reader-type":"stream Message","local-member-id":"dd19be2118b49e84","remote-peer-id":"265f9398ef1e82cd"}
{"level":"info","ts":"2021-11-17T22:15:31.468+0800","caller":"rafthttp/peer.go:335","msg":"stopped remote peer","remote-peer-id":"265f9398ef1e82cd"}
{"level":"info","ts":"2021-11-17T22:15:31.469+0800","caller":"rafthttp/transport.go:355","msg":"removed remote peer","local-member-id":"dd19be2118b49e84","removed-remote-peer-id":"265f9398ef1e82cd"}
{"level":"info","ts":"2021-11-17T22:15:31.469+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"dd19be2118b49e84 switched to configuration voters=(15931974206157528708)"}
{"level":"warn","ts":"2021-11-17T22:15:31.469+0800","caller":"membership/cluster.go:427","msg":"skipped removing already removed member","cluster-id":"3391ef3fb721daae","local-member-id":"dd19be2118b49e84","removed-remote-peer-id":"ea03165512482f69"}
{"level":"panic","ts":"2021-11-17T22:15:31.470+0800","caller":"rafthttp/transport.go:346","msg":"unexpected removal of unknown remote peer","remote-peer-id":"ea03165512482f69","stacktrace":"github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).removePeer\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/transport.go:346\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).RemovePeer\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/transport.go:329\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyConfChange\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:2303\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).apply\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:2135\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyEntries\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1357\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyAll\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1179\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).run.func8\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1111\ngithub.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule.(*fifo).run\n\t/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule/schedule.go:157"}
panic: unexpected removal of unknown remote peer

goroutine 247 [running]:
github.com/rancher/k3s/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0005c6fc0, 0xc00382c140, 0x1, 0x1)
	/go/src/github.com/rancher/k3s/vendor/go.uber.org/zap/zapcore/entry.go:234 +0x58d
github.com/rancher/k3s/vendor/go.uber.org/zap.(*Logger).Panic(0xc000f57630, 0x4f89364, 0x29, 0xc00382c140, 0x1, 0x1)
	/go/src/github.com/rancher/k3s/vendor/go.uber.org/zap/logger.go:227 +0x85
github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).removePeer(0xc000ce6000, 0xea03165512482f69)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/transport.go:346 +0x58c
github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).RemovePeer(0xc000ce6000, 0xea03165512482f69)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp/transport.go:329 +0x7d
github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyConfChange(0xc0010d6a00, 0x1, 0xea03165512482f69, 0x0, 0x0, 0x0, 0x0, 0xc000fccb80, 0x0, 0x0, ...)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:2303 +0x872
github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).apply(0xc0010d6a00, 0xc0015bdfa0, 0x144, 0x157, 0xc000fccb80, 0xc001363858, 0xc001363810, 0x24ae03d)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:2135 +0x59a
github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyEntries(0xc0010d6a00, 0xc000fccb80, 0xc000db2630)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1357 +0xe5
github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyAll(0xc0010d6a00, 0xc000fccb80, 0xc000db2630)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1179 +0x88
github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).run.func8(0x58f5c98, 0xc002d6a200)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/server/v3/etcdserver/server.go:1111 +0x3c
github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule.(*fifo).run(0xc001023ec0)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule/schedule.go:157 +0xf3
created by github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule.NewFIFOScheduler
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/etcd/pkg/v3/schedule/schedule.go:70 +0x13b

```
I play for fun and I have single IP on the node.  
During upgrade, one of the node get error like this, I then remove the node and rejoin it. After all nodes are ready, I reboot them one by one,  the error come back again, and the entire cluster is dead. :(

**Comment by ondrejmo** [comment]
I've also encountered the same problem, apparently a fix was implemented in etcd `0.5.1`. The update to k8s version `1.23` which includes which includes the fix should solve it.

> https://github.com/ahrtr/etcd-issues/tree/master/13466

**Comment by joakimr-axis** [comment]
Did @ondrejmo's suggestion work? Should this Issue still be open?

**Comment by brandond** [comment]
I believe that this should have been resolved by https://github.com/k3s-io/k3s/issues/4940 or one of its equivalent backports that updated the embedded etcd to 3.5.1.
